version: "3.7"

services:
  dashboardserver:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      OPEN_EXCHANGE_APP_ID: $OPEN_EXCHANGE_APP_ID
      NEWSAPI_KEY: $NEWSAPI_KEY
      OPENWEATHER_KEY: $OPENWEATHER_KEY
      METALS_API_KEY: $METALS_API_KEY
      VIRTUAL_HOST: dashboardserver.default
      VIRTUAL_PORT: 8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app:z
    entrypoint: ["/bin/bash", "./scripts/entrypoint.dev.sh"]
    networks:
      - dashboardserver-net

networks:
  dashboardserver-net:
