version: "3.7"

services:
  app:
    build: .
    environment:
      OPEN_EXCHANGE_APP_ID: $OPEN_EXCHANGE_APP_ID
      NEWSAPI_KEY: $NEWSAPI_KEY
      OPENWEATHER_KEY: $OPENWEATHER_KEY
    ports:
      - "8000:8000"
