version: "3.7"

services:
  app:
    build: .
    environment:
      OPEN_EXCHANGE_APP_ID: $OPEN_EXCHANGE_APP_ID
      NEWSAPI_KEY: $NEWSAPI_KEY
      WEATHERBIT_KEY: $WEATHERBIT_KEY 
    ports:
      - "8080:8080"
